<a href="https://colab.research.google.com/github/vikasvr1997/Python_Examples_for_Learing/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import sys

we use numpy instead of lists because they occupy less space and have more features compared to list like lists cannot be multiplied, whereas numpy can be multiplied
numpy is replacement of matlab 
used in plotting
core component of pandas 

In [14]:
a = np.array([1,2,3],np.int8)


In [4]:
a

array([1, 2, 3])

In [5]:
print(a)

[1 2 3]


In [16]:
b = np.array([[1.2,3.4,5.0,5.0],[2.0,3.0,4.0,5.0]],np.int8)
c = np.array([[1,2,3,4,5,6,7,8],[1.0,2.0,5.6,8.9,6,7,9,2]])

In [11]:
# Get Dimension
a.ndim
b.ndim

2

In [12]:
#get shape : provides shape of the matrix array
b.shape


(2, 4)

to know the memory the numpy array is using we use below functions called by function x.dtype

In [15]:
a.dtype

dtype('int8')

In [17]:
b.dtype

dtype('int8')

In [21]:
# get size of the memory in bytes
c.itemsize

8

In [23]:
# Get Total Size
#b.size


8

# accessing specific elements, rows , and columns


In [39]:
a = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]], np.int16)
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


Syntax: numpy.shape(array_name) 
Parameters: Array is passed as a Parameter. 
Return: A tuple whose elements give the lengths of the corresponding array dimensions. 

In [27]:
np.shape(b)

(2, 4)

In [28]:
# get specific element [r,c] -> in the next line of code we get to see that we will cal on a specific element in a array
a[1,4]

13

In [29]:
# get specific row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
# similar to column
a[:,1]

array([ 2, 10])

In [41]:
#  getting a index in more fancy way [start index: end index: step size]
x = a[0,1:7:2]# here we need to understand that in an array a = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]]), such that  a[first row,second element : last element : steppimg it by 2]
# note: never use -2 in index stepping as if you are checking from starting then it can display an empty list so edit the start and end index with negative calls
print(x)

[2 4 6]


In [40]:
# change element in a particular position
a[1,4] = 23

3-D example

In [44]:
a = np.array([[[1,2],[2,4]],[[4,6],[5,7]]],np.int16)
print(a)

[[[1 2]
  [2 4]]

 [[4 6]
  [5 7]]]


In [46]:
# get specific element(work in specific in )
a[0,1,0]# here we are selecting an element from first inner list, then selecting second innner-inner list, then the element position is specified at last 
# changing each position will cause a different effect for the matrix

2

In [47]:
a[:,1,:] = [[9,9],[8,8]]


In [48]:
a


array([[[1, 2],
        [9, 9]],

       [[4, 6],
        [8, 8]]], dtype=int16)

# Initialize different types of variables

In [49]:
# all 0 matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [50]:
# all 1s IN a matrix
np.ones((2,4,4),np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [51]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [53]:
# array full Like any other number (full_like)
np.full_like(a,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]], dtype=int16)

In [54]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.33244619, 0.23961762],
       [0.09129542, 0.01306238],
       [0.50926127, 0.89117633],
       [0.71392165, 0.08502522]])

In [55]:
# is a.shape is to be passed then the statement changes
np.random.random_sample(a.shape)

array([[[0.25877777, 0.9496214 ],
        [0.79374217, 0.14015031]],

       [[0.92367477, 0.19448816],
        [0.66814489, 0.82004936]]])

In [56]:
# random integers np.random.randint(max number , size = (r,c)of matrix)
np.random.randint(12,size=(3,4))

array([[ 9, 11,  4,  7],
       [ 5, 11,  6,  9],
       [ 7,  8,  7,  3]])