<a href="https://colab.research.google.com/github/vikasvr1997/Python_Examples_for_Learing/blob/main/Python_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
s="Hello World" 
print(s)

Hello World


In [ ]:
s=int(input())
print("s={}".format(s))

9
s=9


Control Statements:
conditional Statements:if,elseif(elif),else.
Looping Statements: for,while

Conditional Statements: examples.

In [ ]:
def fun_name():
  a=10
  b=20
  if a == b or a > b :
    print("a is the largest with value {}".format(a))
  else:
    print("B is the largest with value {}".format(b))
fun_name()

B is the largest with value 20


In [ ]:
def fun_name():
  a=10
  b=20
  if a == b or a > b :
    print("a is the largest with value {}".format(a))
  elif a < b:
    print("B is the largest with value {}".format(b))
  else :
    print("None of the above")
fun_name()

B is the largest with value 20


In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
b = np.array([[9,2,4,5],[1,4,2,3],[2,3,4,5]])
print(b)

[[9 2 4 5]
 [1 4 2 3]
 [2 3 4 5]]


In [7]:
b.ndim

2

In [9]:
b.shape

(3, 4)

In [10]:
a.itemsize

8

In [13]:
#get total size
a.nbytes
b.size

12

In [15]:
z=np.array([[1,2,3,4,5,6,7],[2,3,4,5,6,7,8]])
print(z)

[[1 2 3 4 5 6 7]
 [2 3 4 5 6 7 8]]


In [17]:
#get specific element [r,c]
z[0,5]

6

In [18]:
z[0,-2]

6

In [21]:
#gwet a specific row
z[:,0]   # : gets all rows o,1,2 columns

array([1, 2])

In [27]:
#getting a littkle more fancy[startindex:end:stepsize]
print(z[0,1:6:2])



[2 4 6]
[]


In [31]:
print(z[0,1:-2:2])# first element :last element: jumping no

[2 4]


In [33]:
z[1,2]=20
print(z)

[[ 1  2  3  4  5  6  7]
 [ 2  3 20  5  6  7  8]]


In [36]:
z[1,:]=1
print(z)

[[1 2 3 4 5 6 7]
 [1 1 1 1 1 1 1]]


In [39]:
z[1,:1] = [1]
print(z)

[[1 2 3 4 5 6 7]
 [1 1 1 1 1 1 1]]


In [40]:
#3D Example
b=np.array([[[1,2,3],[2,3,4]],[[5,6,0],[7,8,9]]]) 
print(b)

[[[1 2 3]
  [2 3 4]]

 [[5 6 0]
  [7 8 9]]]


In [41]:
#3 to get an specific element in a matrix use arrayname[array list 1,row no,colno]
b[0,1,2]

4

initialize all diff types of arrays

In [59]:
arr = np.array([[1],[2],[3],[4],[5]])
r1 = np.repeat(arr, 5, axis=1)
print(r1)

[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]


In [60]:
output = np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
